### ISSUE TITLE
PyPI release is outdated

### ISSUE THREAD

**Issue by kamurani** [kmayerb/tcrdist3#109]
The latest PyPI release of `tcrdist` is almost 3 years old and thus many code changes in this repository are not included with the installation. 

It would be good if the newer updates to this repository could be reflected in an updated PyPI release, as the install instructions often point new users to use `pip install tcrdist3`.  At the moment I am manually cloning this repository and then installing it as an editable (`pip install -e ~/path/to/tcrdist3`) as the most recent PyPI version is broken (e.g. prior to [this](https://github.com/kmayerb/tcrdist3/commit/4793d8fcffa9aeb88c9f93a9eab0e17bbdec95ee) commit)

**Comment by kmayerb** [comment]
Thanks for your interest in tcrdist3. The latest main branch version of tcrdist3 is now available with pip install tcrdist3==0.3.
