### ISSUE TITLE
Alpha metaclonotypes

### ISSUE THREAD

**Issue by jeremycfd** [kmayerb/tcrdist3#39]
Tried to co-opt the find_metaclonotypes function for alpha chains but ran into the following error:
```
  File "/miniconda3/envs/tcrdist3/lib/python3.8/site-packages/tcrdist/repertoire.py", line 672, in synthesize_vj_matched_background
    raise ValueError("TODO: FUTURE VERSIONS NEED ALPHA(HUMAN)")
ValueError: TODO: FUTURE VERSIONS NEED ALPHA(HUMAN)

```

Should we also start thinking about detecting metaclonotypes using paired data??

**Comment by kmayerb** [comment]
This has been added in the development version. Try reinstall development version until the next tagged release

`pip install git+https://github.com/kmayerb/tcrdist3.git`

See, I have already added alpha for human and mouse now that are both available from olga. MOUSE Olga (alpha) seems to be limited.


https://github.com/kmayerb/tcrdist3/blob/34f8d50e7448b2bf7cf7cd9ab9a2d80759f47240/tcrdist/repertoire.py#L649-L680

**Comment by kmayerb** [comment]
Also to get started with forming metaclonotypes from paired data try:
```python
import pandas as pd
from tcrdist.repertoire import TCRrep

df = pd.read_csv("dash.csv")
tr = TCRrep(cell_df = df,
            organism = 'mouse',
            chains = ['alpha','beta'],
            db_file = 'alphabeta_gammadelta_db.tsv')

tr.pw_alpha_beta = tr.pw_alpha + tr.pw_beta
tr.clone_df['radius'] = 50
from tcrdist.public import _neighbors_variable_radius
tr.clone_df['neighbors'] = _neighbors_variable_radius(
    pwmat = tr.pw_alpha_beta,
    radius_list = tr.clone_df['radius'])
tr.clone_df['neighbors']
```

This will at least quickly give you the neighbors within a fixed radius based on paired alpha and beta distance.

**Comment by kmayerb** [comment]
Also this function could be repurposed to to enable appropriate radii estimation based on background hit frequency and a new matrix like tr.pw_alpha + tr.pw_beta

https://github.com/kmayerb/tcrdist3/blob/02ae5c13f691f83c4e23245959595ebe2ef8323a/tcrdist/centers.py#L12-L91

**Comment by jeremycfd** [comment]
Awesome! You're too fast!! will test asap
