### ISSUE TITLE
Code examples in  documentation

### ISSUE THREAD

**Issue by andreas-wilm** [kmayerb/tcrdist3#47]
Hi Koshlan,

Some code examples in the (hosted version of the) workflow and visualization documentation don't work with the installed version. However, at least the workflow snippets  are all literal includes from the tests, i.e. they likely work when running them from the source tree. Not sure how to reflect the differences in the documentation to be honest.

Please find a list of affected snippets below.

Thanks for open-sourcing such a great tool!

Best, Andreas

### [Workflow: Loading a TCR Dataset](https://tcrdist3.readthedocs.io/en/latest/workflow.html?highlight=cluster#loading-a-tcr-dataset)

     path = os.path.join('tcrdist', 'data', 'covid19')

Should be 

    from tcrdist.paths import path_to_base
    path = os.path.join(path_to_base, 'tcrdist', 'data', 'covid19')

### [Workflow: Simple clustering](https://tcrdist3.readthedocs.io/en/latest/workflow.html?highlight=cluster#simple-clustering)

    tr = TCRrep(... 

is clipped / missing the closing parenthesis (just need changing the include lines)

### [Visualizing](https://github.com/kmayerb/tcrdist3/blob/master/docs/visualizing.rst)

Examples using

    import tcrdist as td
    td.plotting.plot_pairings()

fail with `AttributeError: module 'tcrdist' has no attribute 'plotting'`. Adding the following extra import fixes this:

    from tcrdist import plotting

**Comment by kmayerb** [comment]
Fantastic points. thanks for taking the time to point these out. Updating the docs to reflect these comments.
