### ISSUE TITLE
Distances without cdr3_a_nucseq and cdr3_b_nucseq

### ISSUE THREAD

**Issue by andreas-wilm** [kmayerb/tcrdist3#61]
Hi Koshlan,

According to the [documentation on input requirements](https://tcrdist3.readthedocs.io/en/latest/inputs.html), one or more of the following columns are required and are case-sensitive:

        ‘v_a_gene’, ‘v_b_gene’, ‘v_g_gene’, or ‘v_d_gene’
        ‘j_a_gene’, ‘j_b_gene’, ‘j_g_gene’, or ‘j_d_gene’
        ‘cdr3_a_aa’, ‘cdr3_b_aa’, ‘cdr3_g_aa’, or ‘cdr3a_d_aa’
        ‘cdr3_a_nucseq’, ‘cdr3_b_nucseq, ‘cdr3_g_nucseq’, or ‘cdr3a_d_nucseq’

However, I've used TCRdist3 to compute distances on dataframes without `cdr3_a_nucseq` and `cdr3_b_nucseq`, which seems to have worked fine, but am now wondering whether it did the right thing. 

Apologies for the paranoid question, 
Andreas

**Comment by kmayerb** [comment]
* The nucleotide information is not needed to compute a TCRdist. 
* However, if you don't include cdr3_[abdg]_nucseq, then any set of clones with identical v and j genes and identical cdr3_b_aa (amino acid level identical) will be grouped together. You may or may not want this, but if you want to track clones unique at the nucleotide level cdr3_[abdg]_nucseq would be required. At this point you're a bit of a power user so you may be tracking unique clones with another column.
For more details: https://tcrdist3.readthedocs.io/en/latest/inputs.html#critical-information

```
Tcrdist3 only requires 3 input columns for single chain analysis (i.e., for beta chain cdr3_b_aa and v_b_gene, j_b_gene) and 6 columns for paired chain analysis (i.e., cdr3_b_aa, v_b_gene, j_b_gene, cdr3_a_aa, v_a_gene, and j_a_gene). More columns can be included depending on the application.
```

**Comment by andreas-wilm** [comment]
Thank you. That makes sense. It might be useful to add this to https://tcrdist3.readthedocs.io/en/latest/inputs.html which currently lists the nucseqs as requirement. Best

**Comment by kmayerb** [comment]
Done. Thanks.
