### ISSUE TITLE
Error in calcuating "Radius"

### ISSUE THREAD

**Issue by aoki0623mriid2** [kmayerb/tcrdist3#64]
Dear kmayerb,

I run tcrdist3 in docker using the container "quay.io/kmayerb/tcrdist3:0.1.9"
For calculating "radius", I tried to load un-enriched repertoire data as documentation, but I faced the following error.
I think it is because "unzip" is not installed in the docker container of tcrdist3, but I could not find how to do it.

Best,
Hiroyasu

ts = _default_sampler(organism = "mouse", chain = "beta")()
ruggiero_mouse_beta_t.tsv.sampler.tsv
RUNNING: curl -o /usr/local/lib/python3.8/dist-packages/tcrsampler/db/ruggiero_mouse_sampler.zip https://www.dropbox.com/s/yz8v1c1gf2eyzxk/ruggiero_mouse_sampler.zip?dl=1 -L
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   150    0   150    0     0    622      0 --:--:-- --:--:-- --:--:--   622
100   320  100   320    0     0    407      0 --:--:-- --:--:-- --:--:--     0
100  210k  100  210k    0     0   117k      0  0:00:01  0:00:01 --:--:--  758k
sh: 1: unzip: not found
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/tcrdist/sample.py in _default_tcrsampler_mouse_beta(default_background, default_background_if_missing)
    184     try:
--> 185         t = TCRsampler(default_background=default_background)
    186     except OSError:

/usr/local/lib/python3.8/dist-packages/tcrsampler/sampler.py in __init__(self, default_background)
     72       if not os.path.isfile(path_to_db_bkgd):
---> 73         raise OSError(f'{path_to_db_bkgd} default file not found. Download a default background using python -c "from tcrsampler.setup_db import install_all_next_gen; install_all_next_gen(dry_run = False)"')
     74       else:

OSError: /usr/local/lib/python3.8/dist-packages/tcrsampler/db/ruggiero_mouse_beta_t.tsv.sampler.tsv default file not found. Download a default background using python -c "from tcrsampler.setup_db import install_all_next_gen; install_all_next_gen(dry_run = False)"

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-13-7794098b6ad4> in <module>
----> 1 ts = _default_sampler(organism = "mouse", chain = "beta")()

/usr/local/lib/python3.8/dist-packages/tcrdist/sample.py in _default_tcrsampler_mouse_beta(default_background, default_background_if_missing)
    187         t = TCRsampler()
    188         t.download_background_file(default_background_if_missing)
--> 189         t = TCRsampler(default_background=default_background)
    190     return t
    191

/usr/local/lib/python3.8/dist-packages/tcrsampler/sampler.py in __init__(self, default_background)
     71       path_to_db_bkgd = os.path.join(path_to_db, self.default_bkgd)
     72       if not os.path.isfile(path_to_db_bkgd):
---> 73         raise OSError(f'{path_to_db_bkgd} default file not found. Download a default background using python -c "from tcrsampler.setup_db import install_all_next_gen; install_all_next_gen(dry_run = False)"')
     74       else:
     75         bar = IncrementalBar(f'Loading {self.default_bkgd}', max = 2, suffix='%(percent)d%%')

OSError: /usr/local/lib/python3.8/dist-packages/tcrsampler/db/ruggiero_mouse_beta_t.tsv.sampler.tsv default file not found. Download a default background using python -c "from tcrsampler.setup_db import install_all_next_gen; install_all_next_gen(dry_run = False)"

**Comment by kmayerb** [comment]
Thanks for alerting us of this issue, I think it would be a good idea to add unzip to the docker image. I am adding that so it will be pre-installed in tcrdist:0.2.3 

For now a quick fix would be the following:

```
docker run -it quay.io/kmayerb/tcrdist3:0.2.2
```

Then within the container:

```
apt-get install unzip
```

Then this works just fine:

```python
from tcrdist.sample import _default_sampler
ts = _default_sampler(organism = "mouse", chain = "beta")()
```

**Comment by aoki0623mriid2** [comment]
Thank you for your kined reply.

I found the code run successfully with your instruction.
Thank you so much for your kindness.

**Comment by kmayerb** [comment]
No problem at all. Thank you for bringing this issue to our attention.
