### ISSUE TITLE
Guidance on using find_metaclonotypes (specifically on bkgd_cntl_nn2 function)

### ISSUE THREAD

**Issue by elulu3** [kmayerb/tcrdist3#82]
Hi, I have been following along the find_metaclonotypes function provided in the documentation but found myself stuck on how to use the bkgd_cntl_nn2 function. My antigen-enriched dataset is around 100k rows and so in the initialization of the TCRrep class, I have set compute_distances = FALSE and ran compute_sparse_rect_distances. If I am understanding correctly, this outputs a tr.rw_beta result rather than a tr.pw_beta result. And so here lies my confusion because bkgd_cntl_nn2 seems to require a pw_mat_str input but I don't have a pw_beta result computed. What should I be providing to this parameter ('rw_beta'?)? What exactly is the difference between pw_beta and rw_beta?

**Comment by elulu3** [comment]
Received an answer - find_metaclonotypes is not meant to be run on 100k rows. I believe the recommendation was <=15,000 clones.

**Comment by linqy-immune** [comment]
Hello, @elulu3 
I'm sorry to bother you but I have encountered a similar question like yours.
I am a little curious about whether datasets without antigen-epitope information can be applied to find meta-clonotype?
Could you please tell me how you solve the problem or how do you choose the 15,000 clones for meta-clonotype function?
If it is convenient for you, please offer me some help, I have been stuck here for a long time.
Thanks and best regards,
Linqy
