### ISSUE TITLE
How to compare clonal similarity between different groups?

### ISSUE THREAD

**Issue by sc30301** [kmayerb/tcrdist3#84]
Hi, 

I have TCR data from 5 different conditions and want to use TCRdist3 to show, for example, that clones in group 1 are more similar to those in groups 2 and 3, while clones in group 4 are more similar to group 5. I have run the metaclonotype pipeline but unsure how to utilize the results.

**Comment by kmayerb** [comment]
Compute the pairwise distances between all clones. Then compute average distance within and between groups. If you attempt and share some code I might be able to provide additional insight.
