### ISSUE TITLE
Error with using with the newest version of python

### ISSUE THREAD

**Issue by rutha32** [kmayerb/tcrdist3#93]
Hi when I do the pip install, I have issues as I have the newest version of python 

This is the part of the error code
RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.

Is there a way around this error

**Comment by bchain** [comment]
I am also having this problem.

**Comment by kmayerb** [comment]
We have never tested installation of tcrdist3 on versions of Pyhton > 3.9.
We will look into whether it can be installed on later versions.

In the meantime you might using a miniconda environment

```
conda create -n p38 python=3.8
conda activate p38
pip install XXXXX
```
